In [ ]:
def test_sim_timeline(self):
    """Check the a scheduled task returns the correct time"""
    # Task params
    param_t_delay = [0, 1, 5]
    param_t_interval = [1, 3, 5]  # TODO should it work with 0?

    # Sim_timeline params
    param_inputs = [(0, 100)]

    for t_interval in param_t_interval:
        for t_delay in param_t_delay:

            for t_start, t_end in param_inputs:

                # with self.subTest():
                # Arrange
                task = ScheduledTask(t_delay=t_delay, t_interval=t_interval)

                if t_delay == 0:
                    delay = []
                else:
                    delay = np.linspace(t_interval, 0, t_delay + 1)

                expected = np.concatenate(
                    [
                        delay,
                        np.tile(
                            np.linspace(t_interval, 0, t_interval + 1),
                            int((t_end - t_delay) / t_interval) + 1,
                        ),
                    ]
                )

                expected = expected[t_start : t_end + 1]

                # Act
                schedule = sim_timeline(t_start=t_start, t_end=t_end)

    return expected, schedule

In [18]:
import sys
import os
sys.path.append(os.path.dirname(os.getcwd()))

import numpy as np
import math

from pof.task import Task, ScheduledTask, ConditionTask, Inspection

In [72]:
# inputs
t_delay = 0
t_interval = 1
t_start = 0
t_end = 100

In [73]:
# with self.subTest():
# Arrange
task = ScheduledTask(t_delay=t_delay, t_interval=t_interval)
task.__dict__

{'_name': 'scheduled_task',
 'task_type': 'Factory method only',
 'trigger': 'time',
 'active': True,
 '_package': NotImplemented,
 '_impacts_parent': NotImplemented,
 '_impacts_children': False,
 'cost': 0,
 'labour': NotImplemented,
 'spares': NotImplemented,
 'equipment': NotImplemented,
 'consequence': <pof.consequence.Consequence at 0x268483a3ac0>,
 'p_effective': 1,
 'triggers': {},
 'impacts': {},
 'state': NotImplemented,
 't_completion': [],
 'cost_completion': [],
 '_timeline': NotImplemented,
 '_t_interval': 1,
 '_t_delay': 1}

In [74]:
if t_delay == 0:
    delay = []
else:
    delay = np.linspace(t_interval, 0, t_delay + 1)

delay

array([1., 0.])

In [75]:
expected = np.concatenate(
    [
        delay,
        np.tile(
            np.linspace(t_interval, 0, t_interval + 1),
            int((t_end - t_delay) / t_interval) + 1,
        ),
    ]
)
expected

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

In [76]:
expected = expected[t_start : t_end + 1]
expected

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.])

In [15]:
# Act
schedule = task.sim_timeline(t_start=t_start, t_end=t_end)
schedule

array([6., 5., 4., 3., 2., 1., 0., 9., 8., 7., 6., 5., 4., 3., 2., 1., 0.,
       9., 8., 7., 6., 5., 4., 3., 2., 1., 0., 9., 8., 7., 6., 5., 4., 3.,
       2., 1., 0., 9., 8., 7., 6., 5., 4., 3., 2., 1., 0., 9., 8., 7., 6.])

In [77]:
    def sim_timeline(t_end, t_start=0, *args, **kwargs):

        #if self.active:

        schedule = np.tile(
            np.linspace(t_interval, 0, int(t_interval)+1),
            math.ceil(max((t_end - t_delay), 0) / t_interval),
        )

        if t_delay > 0:
            t_delay = min(t_delay, t_end)
            sched_start = np.linspace(t_interval, 0, t_delay + 1)
            schedule = np.concatenate((sched_start, schedule))
        
        schedule = schedule[t_start : t_end + 1]

        else:
            schedule = np.full(t_end - t_start + 1, -1)

        return schedule

SyntaxError: invalid syntax (<ipython-input-77-52372da2de0f>, line 17)

In [78]:
schedule = np.tile(
    np.linspace(t_interval, 0, int(t_interval)+1),
    math.ceil(max((t_end - t_delay), 0) / t_interval),
)
schedule

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

In [79]:
if t_delay > 0:
    t_delay = min(t_delay, t_end)
    sched_start = np.linspace(t_interval, 0, t_delay + 1)
    schedule = np.concatenate((sched_start, schedule))
schedule

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

In [80]:
schedule = schedule[t_start : t_end + 1]
schedule

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.])

In [81]:
schedule == expected

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])